name: CI

on: 
  push:  # 1. push될 때마다 실행
  pull_request:  # (추가 시도) main 브랜치에 pull request 발생 시 실행
    branches: [main]
  workflow_dispatch:  # (추가 시도) 수동 실행 기능 추가

jobs:
  Test:
    runs-on: ubuntu-latest  # 2. 우분투 최신 버전에서 실행
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]  # 3. 파이썬 3.9, 3.10 버전에서 테스트
        
    steps:
      # 4. checkout 액션 실행
      - uses: actions/checkout@v4

      # 5-1. tensorflow 2.10 설치
      - name: Install Tensorflow 2.10
        run: pip install tensorflow==2.10

      # 5-2. numpy 1.21 설치
      - name: Install NumPy 1.21
        run: pip install numpy==1.21

      # 6. main.py 작동 테스트
      - name: Run main.py
        run: python main.py