name: Python CI

# push 이벤트 발생 시 워크플로우 실행
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # 우분투 최신버전 사용

    strategy:
      matrix:
        python-version: [3.9, 3.10]  # 파이썬 3.9, 3.10 버전에서 테스트

    steps:
    # 1. checkout action을 통해 레포지토리 가져오기
    - name: Check out repository
      uses: actions/checkout@v4

    # 2. 파이썬 버전 설정 및 필수 패키지 설치
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==2.10 numpy==1.21

    # 3. main.py가 작동하는지 테스트
    - name: Run main.py
      run: |
        python main.py